version: '3.1'

services:

  db:
    image: postgresql:14.10
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
    ports:
      - 3307:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080